n1 = int(input('Digite o 1º número: '))
n2 = int(input('Digite o 2º número: '))
n3 = int(input('Digite o 3º número: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print('\nO maior número é {} e o menor é: {} ' .format(maior,menor))
